#!/usr/bin/env python3

# ───────────────────────────────────────────────────────────────
# File: qlacs_ghz_qlz_v2_eng_analyzer.py
# Purpose: HARPIA Benchmark Analyzer and Generator
# Author: deywe@QLZ | Processes CSV generated by the simulation script.
# ───────────────────────────────────────────────────────────────
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import matplotlib.pyplot as plt
import os
import sys
import numpy as np

# 🔧 Configure output folder for graphs
OUTPUT_DIR = "benchmark_analysis"
os.makedirs(OUTPUT_DIR, exist_ok=True)


def input_path():
    """Prompts the user for the full path to the log CSV file."""
    print("=" * 60)
    print("HARPIA BENCHMARK ANALYZER (SPHY COHERENCE)")
    print("=" * 60)
    path = input("📁 Enter the FULL path to the CSV file for analysis: ")
    return path


def analyze_and_generate_benchmark(csv_path):
    """
    Loads the CSV, calculates stability metrics, and generates the evolution graph.
    """
    if not os.path.exists(csv_path):
        print(f"\n❌ Error: File not found at path: {csv_path}")
        sys.exit(1)

    try:
        # Load the CSV using pandas
        df = pd.read_csv(csv_path)
    except Exception as e:
        print(f"\n❌ Error reading the CSV file: {e}")
        sys.exit(1)

    # 1. Obtain Basic Metrics
    
    # Determine the number of Qubits from the column headers
    qubit_cols = [col for col in df.columns if col.startswith('Qubit_')]
    num_qubits = len(qubit_cols)
    
    total = len(df)
    validos = (df['Accepted'] == '✅').sum()
    acceptance_rate = 100 * (validos / total)
    
    # Main coherence column
    coherence_column = 'SPHY (%)'
    
    if coherence_column not in df.columns:
        print(f"\n❌ Error: Column '{coherence_column}' not found in the CSV.")
        sys.exit(1)

    # 2. Calculation of Stability Metrics (Identical to the Simulation Script)
    
    sphy_evolution = df[coherence_column].tolist()
    
    if sphy_evolution:
        mean_coherence = np.mean(sphy_evolution)
        # Use np.std for greater robustness, ensuring ddof=1 for sample standard deviation
        stability_stdev = np.std(sphy_evolution, ddof=1) if len(sphy_evolution) > 1 else 0.0
        stability_variance = stability_stdev ** 2
    else:
        mean_coherence = 0.0
        stability_stdev = 0.0
        stability_variance = 0.0

    # 3. Printing the Metrics
    print("\n" + "—" * 60)
    print(f"HARPIA BENCHMARK ANALYSIS (Q={num_qubits}, FRAMES={total:,})")
    print("—" * 60)
    print(f"✅ Accepted GHZ States: {validos}/{total} | {acceptance_rate:.2f}%")
    print("\nHARPIA STABILITY METRICS (SPHY COHERENCE)")
    print(f"🎯 Mean Coherence (Mean): {mean_coherence:.6f}%")
    print(f"⚖️ Standard Deviation (Stdev): {stability_stdev:.6f}")
    print(f"🔬 Variance (Variance): {stability_variance:.6f}")
    print("—" * 60)
    
    # 4. Generation of the Graph (Identical to the Simulation Script)
    
    base_name = os.path.basename(csv_path).replace('.csv', '')
    nome_fig = os.path.join(OUTPUT_DIR, f"{base_name}_analysis_graph.png")

    plt.figure(figsize=(12, 5))
    
    # SPHY Coherence evolution line
    plt.plot(df['Frame'], df[coherence_column], color="darkcyan", label="⧉ SPHY Coherence")
    
    # Scatter plot colored by acceptance
    scatter_colors = df['Accepted'].apply(lambda x: 'green' if x == '✅' else 'red')
    plt.scatter(
        df['Frame'], df[coherence_column],
        c=scatter_colors, 
        s=8, alpha=0.6
    )
    
    # Threshold Line
    plt.axhline(90, color='gray', linestyle="dotted", linewidth=1, label="Threshold")
    
    # Titles and Labels
    plt.title(f"📡 HARPIA SPHY Evolution • {num_qubits} Qubits • {total:,} Frames (Analysis)")
    plt.xlabel("Frames")
    plt.ylabel("SPHY Coherence (%)")
    plt.grid(True, linestyle="--", alpha=0.3)
    plt.legend()
    plt.tight_layout()
    
    # Save and show the graph
    plt.savefig(nome_fig, dpi=300)
    print(f"📊 Analysis graph saved as: {nome_fig}")
    plt.show()

# Entry point
if __name__ == "__main__":
    # Check if the pandas library is installed
    try:
        import pandas as pd
    except ImportError:
        print("❌ The 'pandas' library is not installed. Install with: pip install pandas")
        sys.exit(1)
        
    csv_path = input_path()
    analyze_and_generate_benchmark(csv_path)